site_name: NewbModding1710 - Minecraft Mod 1.7.10 开发教学
site_author: "AmarokIce"
site_description: "狼在凤梨田里编写的 1.7.10 开发教学"
copyright: Copyright © 2019-2025 AmarokIce
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/AmarokIce/
          name: Github
    generator: false

nav:
    - 入门开发:
          - 前言与准备: index.md
          - 部分重要概念: Core.md
          - 主要类与代理: Mod.md
          - 物品:
                - 第一个物品: common/item/FirstItem.md
                - ItemStack: common/item/ItemStack.md
                - 创造模式物品栏: common/item/TagGroup.md
                - 创建一个食物: common/item/ItemFood.md
                - 工具与武器: common/item/ToolAndWeapon.md
                - 防具: common/item/Armors.md
                - 工具与防具材质: common/item/Material.md
                - 元数据区分的物品: common/item/MetaItem.md
          - 方块:
                - 第一个方块: common/block/FirstBlock.md
                - 方块朝向: common/block/BlockFacing.md
                - 方块的特殊渲染: common/block/RenderBlock.md
          - 方块实体:
                - 方块与方块实体: common/tile/TileBlock.md
                - 工作中方块: common/tile/WorkingBlock.md
                - 数据同步与封包: common/tile/ProxyPacket.md
          - 文本组件: common/ChatComponent.md
          - 合成表与矿物辞典:
                - 注册工作台合成表: common/craft/Crafting.md
                - 注册熔炉合成表: common/craft/FurnaceCrafting.md
                - 注册酿造合成表: common/craft/BrewingRecipe.md
                - 矿物辞典与注册矿物辞典: common/craft/OreDict.md
          - 生物伤害类型: common/DamageType.md
          - 网络通讯: common/NetWork.md
          - UI 与 HUD:
                - GameUI: common/gui/GUI.md
                - HUD: common/gui/HUD.md
          - 事件:
                - 事件，广播与订阅: common/event/Event.md
                - 发送事件: common/event/InitEvent.md
          - 药水效果:
                - 药水与准备工作: common/effect/ID.md
                - 药水创建: common/effect/Effect.md
          - 生物群系: common/Biome.md
          - 指令:
                - 服务端上的指令: common/command/ServerCommand.md
                - 客户端上的指令: common/command/ClientCommand.md
    - 进阶开发:
          - 准备发车: advanced/index.md
          - 物品:
                - 按照数量变换图标的物品: advanced/item/MagicItem.md
                - NBT 区分的物品: advanced/item/NbtItem.md
                - 创建一个“钱包”: advanced/item/WalletItem.md
          - 方块:
                - 分离注册的方块与方块物品: advanced/block/BlockItem.md
                - 带有元数据的方块: advanced/block/MetaBlock.md
          - 生物:
                - 生物与 AI: advanced/entity/Entity.md
                - 生物渲染: advanced/entity/EntityRender.md
          - 世界:
                - 树与树苗: advanced/world/Tree.md
                - 世界装饰器: advanced/world/WorldGen.md
                - 矿物生成: advanced/world/OreGen.md
                - 结构: advanced/world/Struction.md
                - 世界: advanced/world/World.md
          - 与常见模组联动:
                - 兼容 NEI: advanced/lib/Nei.md
                - 兼容 Waila: advanced/lib/Waila.md
                - 使用 GeckoLib: advanced/lib/GeoModel.md
          - OBJ 模型:
                - 方块实体渲染器(BlockEntityRenderer): advanced/obj/TileRenderer.md
                - GL11 与资源路径: advanced/obj/ObjRender.md
                - 手持物品的渲染: advanced/obj/ItemObj.md
          - Mixin 与 ASM:
                - Mixin:
                    - 注入回调器: advanced/mixin/Inject.md
                    - 拓宽访问器: advanced/mixin/Access.md
                    - 唯一修饰符: advanced/mixin/Unique.md
                - ASM:
                    - ASM 入门: advanced/asm/ASM.md
                    - ASM 定位: advanced/asm/patch.md
    - 凤梨文档:
          - 欢迎使用 Pineapple TogoCups!: togocup/index.md
          - 凤梨通灵术:
                - 自动 Config: togocup/ppc/Config.md
                - 合成表匹配: togocup/ppc/MatchUtil.md
                - 简单容器: togocup/ppc/SimpleInventory.md
          - 凤梨标签:
                - 添加标签: togocup/tags/AddTags.md
                - 使用标签: togocup/tags/UsingTags.md
                - 使标签与矿物辞典兼容: togocup/tags/OreDict.md
          - WolfTailUI:
                - 吐司: togocup/wui/Toast.md
                - UIStyle: togocup/wui/Style.md
                - UIBased: togocup/wui/UI.md
    # - 回到凤梨田: https://wolf.snowlyicewolf.club/

theme:
    name: material
    logo: assets/ricon.png
    favicon: assets/ricon.png
    language: zh
    features:
        - header.autohide
        - navigation.tabs
        - content.code.annotate
        - content.code.copy
    palette:
        - scheme: default
          toggle:
              icon: material/weather-night
              name: 关闭月亮

        - scheme: slate
          toggle:
              icon: material/weather-sunny
              name: 打开月亮
    icon:
        admonition:
            note: octicons/tag-16
            abstract: octicons/checklist-16
            info: octicons/info-16
            tip: octicons/squirrel-16
            success: octicons/check-16
            question: octicons/question-16
            warning: octicons/alert-16
            failure: octicons/x-circle-16
            danger: octicons/zap-16
            bug: octicons/bug-16
            example: octicons/beaker-16
            quote: octicons/quote-16

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
    - pymdownx.details
    - pymdownx.superfences

plugins:
    - search
    - search:
          lang: zh
